name: soccer_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.1.beta <3.0.0"

dependencies:
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  lottie: ^1.2.1
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Black.ttf
        weight: 900
      - asset: assets/fonts/Montserrat-BlackItalic.ttf
        weight: 900
      - asset: assets/fonts/Montserrat-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        weight: 800
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-BoldItalic.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-MediumItalic.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/Montserrat-LightItalic.ttf
        weight: 300
      - asset: assets/fonts/Montserrat-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        weight: 200
      - asset: assets/fonts/Montserrat-Thin.ttf
        weight: 100
      - asset: assets/fonts/Montserrat-ThinItalic.ttf
        weight: 100
