// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgLWB_nc8GR5JzaPSSLHLMGZCz-9MFHos',
    appId: '1:496202967400:web:f8b930964cea7c78d14edd',
    messagingSenderId: '496202967400',
    projectId: 'soccer-8769f',
    authDomain: 'soccer-8769f.firebaseapp.com',
    storageBucket: 'soccer-8769f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMyBE8pGzAg4gIu_lcYr9Ru1_vGewLO0U',
    appId: '1:496202967400:android:f41f024d2724dfbbd14edd',
    messagingSenderId: '496202967400',
    projectId: 'soccer-8769f',
    storageBucket: 'soccer-8769f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjMBdw8V2B9l69GbMvPbTG6ykIf40a_as',
    appId: '1:496202967400:ios:1055c475a93620c5d14edd',
    messagingSenderId: '496202967400',
    projectId: 'soccer-8769f',
    storageBucket: 'soccer-8769f.appspot.com',
    iosClientId: '496202967400-23r243c7blirvtd9o9k5sjvqu8qj1jfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.soccerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjMBdw8V2B9l69GbMvPbTG6ykIf40a_as',
    appId: '1:496202967400:ios:3daf674b5f3a857ed14edd',
    messagingSenderId: '496202967400',
    projectId: 'soccer-8769f',
    storageBucket: 'soccer-8769f.appspot.com',
    iosClientId: '496202967400-4g8uvkpo75i8mchoji0t306g1sgjktl4.apps.googleusercontent.com',
    iosBundleId: 'Y',
  );
}
